###
# Copyright (c) 2017 Eclipse Foundation and others. # 
# This program and the accompanying materials are made available 
#
# under the terms of the Eclipse Public License 2.0 which accompanies 
# this distribution, and is available at http://eclipse.org/legal/epl-2.0
###

version: '3'
services:
  php5.3:
    build: ./php/php5.3
    ports:
       - 80
  php5.5:
    build: ./php/php5.5
    ports:
       - 80
  php5.6:
    build: ./php/php5.6
    ports:
       - 80
  php7.0:
    build: ./php/php7.0
    ports:
       - 80
  planeteclipse:
    build: ./planeteclipse
    ports:
      - 80
    environment:
      PLANETECLIPSE_HTTP_SERVER: "false"
      PLANETECLIPSE_UPDATE: "false"
